# Use Node.js 22 as the base image
FROM node:22-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy package files
COPY package*.json ./
COPY tsconfig.json ./

# Install dependencies
RUN npm install

# Expose the port your app runs on
EXPOSE 8000

# Start the application from the compiled JavaScript in dist
CMD [ "npm", "run", "dev" ]